services:
  api:
    container_name: sudoku_api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - local.env
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
  migrate:
    container_name: sudoku_migrate
    build: .
    depends_on:
      - db
    entrypoint: ["migrate"]
    env_file:
      - local.env
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
  db:
    container_name: postgres
    image: postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/data/postgres"
    ports:
      - "5332:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  pghero:
    image: ankane/pghero
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:12345@db:5432/postgres"
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    driver: bridge

volumes:
  postgres-data: {}