services:
  api:
    container_name: sudoku_api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_MIGRATIONS_PATH: "migrations/sql"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "12345"
      DATABASE_NAME: "postgres"
      API_PORT: "8080"
      AUTH_ITERATIONS: "3"
      AUTH_MEMORY: "64"
      AUTH_PARALLELISM: "1"
      AUTH_KEY_LEN: "32"
      AUTH_SALT_LEN: "16"
      ENV: "docker"
  migrate:
    build: .
    depends_on:
      - db
    command: ["migrate"]
    environment:
      DATABASE_MIGRATIONS_PATH: "migrations/sql"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "12345"
      DATABASE_NAME: "postgres"
      API_PORT: "8080"
      AUTH_ITERATIONS: "3"
      AUTH_MEMORY: "64"
      AUTH_PARALLELISM: "1"
      AUTH_KEY_LEN: "32"
      AUTH_SALT_LEN: "16"
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/data/postgres"
    ports:
      - "5332:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  default:
    driver: bridge

volumes:
  postgres-data: {}